// Autogenerated from supabase; run "npm run types:generate" to generate most recent ver
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      club_memberships: {
        Row: {
          club_id: number
          joined_at: string
          membership_id: number
          role: string | null
          user_id: number
        }
        Insert: {
          club_id: number
          joined_at?: string
          membership_id?: number
          role?: string | null
          user_id: number
        }
        Update: {
          club_id?: number
          joined_at?: string
          membership_id?: number
          role?: string | null
          user_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "club_memberships_club_id_fkey"
            columns: ["club_id"]
            isOneToOne: false
            referencedRelation: "clubs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "club_memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      clubs: {
        Row: {
          category: string
          club_name: string
          created_at: string
          created_by: number
          description: string | null
          experience_level: number | null
          experience_points: number | null
          id: number
          locations: string[]
          logo_url: string | null
          member_ids: string[] | null
          sprite_url: string | null
        }
        Insert: {
          category: string
          club_name: string
          created_at?: string
          created_by: number
          description?: string | null
          experience_level?: number | null
          experience_points?: number | null
          id?: number
          locations: string[]
          logo_url?: string | null
          member_ids?: string[] | null
          sprite_url?: string | null
        }
        Update: {
          category?: string
          club_name?: string
          created_at?: string
          created_by?: number
          description?: string | null
          experience_level?: number | null
          experience_points?: number | null
          id?: number
          locations?: string[]
          logo_url?: string | null
          member_ids?: string[] | null
          sprite_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "clubs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      event_attendance: {
        Row: {
          bonus_xp: number | null
          checked_in_at: string | null
          club_id: number
          created_at: string
          event_id: number
          id: number
          user_id: number
          xp_given: number | null
        }
        Insert: {
          bonus_xp?: number | null
          checked_in_at?: string | null
          club_id: number
          created_at?: string
          event_id: number
          id?: number
          user_id: number
          xp_given?: number | null
        }
        Update: {
          bonus_xp?: number | null
          checked_in_at?: string | null
          club_id?: number
          created_at?: string
          event_id?: number
          id?: number
          user_id?: number
          xp_given?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "event_attendance_club_id_fkey"
            columns: ["club_id"]
            isOneToOne: false
            referencedRelation: "clubs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_attendance_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_attendance_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          base_xp: number | null
          bonus_xp: number | null
          club_id: number
          created_at: string
          description: string | null
          event_date: string
          event_name: string
          id: number
          latitude: number
          longitude: number
        }
        Insert: {
          base_xp?: number | null
          bonus_xp?: number | null
          club_id: number
          created_at?: string
          description?: string | null
          event_date: string
          event_name: string
          id?: number
          latitude: number
          longitude: number
        }
        Update: {
          base_xp?: number | null
          bonus_xp?: number | null
          club_id?: number
          created_at?: string
          description?: string | null
          event_date?: string
          event_name?: string
          id?: number
          latitude?: number
          longitude?: number
        }
        Relationships: [
          {
            foreignKeyName: "events_club_id_fkey"
            columns: ["club_id"]
            isOneToOne: false
            referencedRelation: "clubs"
            referencedColumns: ["id"]
          },
        ]
      }
      friends: {
        Row: {
          created_at: string
          friend_id: number
          id: number
          status: string
          user_id: number
        }
        Insert: {
          created_at?: string
          friend_id: number
          id?: number
          status: string
          user_id: number
        }
        Update: {
          created_at?: string
          friend_id?: number
          id?: number
          status?: string
          user_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "friends_friend_id_fkey"
            columns: ["friend_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friends_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          club_ids: string[] | null
          created_at: string
          email: string
          experience_level: number | null
          experience_points: number | null
          first_name: string
          id: number
          last_name: string
          mon_url: string | null
          user_id: string
          user_type: string
        }
        Insert: {
          avatar_url?: string | null
          club_ids?: string[] | null
          created_at?: string
          email: string
          experience_level?: number | null
          experience_points?: number | null
          first_name: string
          id?: number
          last_name: string
          mon_url?: string | null
          user_id: string
          user_type: string
        }
        Update: {
          avatar_url?: string | null
          club_ids?: string[] | null
          created_at?: string
          email?: string
          experience_level?: number | null
          experience_points?: number | null
          first_name?: string
          id?: number
          last_name?: string
          mon_url?: string | null
          user_id?: string
          user_type?: string
        }
        Relationships: []
      }
      xp_levels: {
        Row: {
          created_at: string | null
          level: number
          max_xp: number | null
          min_xp: number
          title: string | null
        }
        Insert: {
          created_at?: string | null
          level: number
          max_xp?: number | null
          min_xp: number
          title?: string | null
        }
        Update: {
          created_at?: string | null
          level?: number
          max_xp?: number | null
          min_xp?: number
          title?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// Create helper types for easier usage
export type User = Database['public']['Tables']['users']['Row']
export type UserInsert = Database['public']['Tables']['users']['Insert']
export type UserUpdate = Database['public']['Tables']['users']['Update']

export type Club = Database['public']['Tables']['clubs']['Row']
export type ClubInsert = Database['public']['Tables']['clubs']['Insert']
export type ClubUpdate = Database['public']['Tables']['clubs']['Update']

//
